---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Allow HTTP
  ufw:
    rule: allow
    port: http
    proto: tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: https
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny 