---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create Nginx configuration directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Configure Nginx as reverse proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  notify: restart nginx

- name: Enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes 