---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  apt:
    name:
      - curl
      - wget
      - git
      - python3-pip
      - python3-dev
      - software-properties-common
    state: present

- name: Set timezone
  timezone:
    name: UTC

- name: Configure NTP
  apt:
    name: ntp
    state: present

- name: Enable and start NTP service
  service:
    name: ntp
    state: started
    enabled: yes 