---
- name: Create monitoring directory
  file:
    path: /opt/monitoring
    state: directory
    mode: '0755'

- name: Download and install Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/monitoring
    remote_src: yes

- name: Create Node Exporter service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'

- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Start and enable Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes 