---
- name: Check Application Status and Logs
  hosts: webservers
  become: yes
  tasks:
    - name: Check if Docker containers are running
      shell: docker ps
      register: docker_ps

    - name: Display Docker containers
      debug:
        var: docker_ps.stdout_lines

    - name: Get application logs
      shell: docker logs $(docker ps -q --filter name=webapp)
      register: app_logs

    - name: Display application logs
      debug:
        var: app_logs.stdout_lines

    - name: Check Nginx access logs
      shell: tail -n 20 /var/log/nginx/webapp_access.log
      register: nginx_access
      ignore_errors: yes

    - name: Display Nginx access logs
      debug:
        var: nginx_access.stdout_lines 